// Package index implements `regesto index` (PLAN 1.b): regenerate INDEX.md
// and knowledge/topics/ from knowledge/facts/. Both are generated artifacts
// (SCHEMA.md) — rebuilt, never hand-edited.
package index

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/prof18/regesto/internal/facts"
)

const generatedHeader = "> GENERATED by `regesto index` from `knowledge/facts/` — do not edit by hand;\n" +
	"> edits are lost on the next rebuild. Fix the underlying facts instead\n" +
	"> (SCHEMA.md, Generated artifacts).\n"

// Result holds the generated artifacts as strings, so tests can assert on
// content without touching disk.
type Result struct {
	IndexMD string
	// TopicPages maps topic slug → page content, one file per slug under
	// knowledge/topics/.
	TopicPages map[string]string
}

// Build generates INDEX.md and the topic pages. Listings show active and
// proposed claims (proposed tagged); superseded claims appear in the status
// counts and vocabulary usage only — SCHEMA.md says to ignore them unless
// asked about history.
func Build(all []facts.Fact) Result {
	var b strings.Builder
	b.WriteString("# INDEX\n\n")
	b.WriteString(generatedHeader)
	b.WriteString("> Sections are ordered global first, then one per project, so hooks can\n")
	b.WriteString("> inject a slice rather than the whole file.\n\n")

	live := make([]facts.Fact, 0, len(all))
	for _, f := range all {
		if f.Status != facts.StatusSuperseded {
			live = append(live, f)
		}
	}

	// Global first, then one section per project.
	b.WriteString("## Global\n\n")
	writeFactList(&b, scopeFacts(live, ""))

	for _, project := range projectNames(live) {
		fmt.Fprintf(&b, "## Project: %s\n\n", project)
		writeFactList(&b, scopeFacts(live, project))
	}

	// Controlled vocabulary: every (subject, relation) pair in use — the
	// defence against silent vocabulary drift (PLAN 1.b). Counts include
	// superseded facts: a pair with history is still a pair in use.
	b.WriteString("## Controlled vocabulary\n\n")
	b.WriteString("Reuse these `(subject, relation)` pairs exactly; check here before minting\na new pair (SCHEMA.md).\n\n")
	b.WriteString("| subject | relation | facts |\n|---|---|---|\n")
	for _, pair := range vocabulary(all) {
		fmt.Fprintf(&b, "| %s | %s | %d |\n", pair.subject, pair.relation, pair.count)
	}
	b.WriteString("\n")

	topics := topicMap(live)
	b.WriteString("## Topics\n\n")
	if len(topics) == 0 {
		b.WriteString("(none)\n")
	}
	for _, slug := range sortedKeys(topics) {
		fmt.Fprintf(&b, "- [[%s]] — %d fact(s)\n", slug, len(topics[slug]))
	}
	b.WriteString("\n")

	b.WriteString("## Status\n\n")
	b.WriteString("| status | count |\n|---|---|\n")
	counts := map[string]int{}
	for _, f := range all {
		counts[f.Status]++
	}
	for _, status := range []string{facts.StatusActive, facts.StatusProposed, facts.StatusSuperseded} {
		fmt.Fprintf(&b, "| %s | %d |\n", status, counts[status])
	}

	pages := make(map[string]string, len(topics))
	for slug, members := range topics {
		pages[slug] = topicPage(slug, members)
	}
	return Result{IndexMD: b.String(), TopicPages: pages}
}

// Write puts INDEX.md at the KB root and rewrites knowledge/topics/: every
// top-level generated .md page is replaced, stale pages are removed. Only
// generated artifacts are touched — facts are never written here.
func Write(kbRoot string, r Result) error {
	if err := os.WriteFile(filepath.Join(kbRoot, "INDEX.md"), []byte(r.IndexMD), 0o644); err != nil {
		return err
	}
	topicsDir := filepath.Join(kbRoot, "knowledge", "topics")
	if err := os.MkdirAll(topicsDir, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(topicsDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") {
			if err := os.Remove(filepath.Join(topicsDir, e.Name())); err != nil {
				return err
			}
		}
	}
	for slug, content := range r.TopicPages {
		if err := os.WriteFile(filepath.Join(topicsDir, slug+".md"), []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func writeFactList(b *strings.Builder, list []facts.Fact) {
	if len(list) == 0 {
		b.WriteString("(none)\n\n")
		return
	}
	for _, f := range list {
		tag := ""
		if f.Status == facts.StatusProposed {
			tag = "[proposed] "
		}
		fmt.Fprintf(b, "- `%s` — %s%s (%s)\n", f.ID, tag, f.Title, f.RelPath)
	}
	b.WriteString("\n")
}

// scopeFacts returns facts for one scope, sorted by id. project == "" means
// global.
func scopeFacts(list []facts.Fact, project string) []facts.Fact {
	var out []facts.Fact
	for _, f := range list {
		if f.ProjectName() == project {
			out = append(out, f)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

func projectNames(list []facts.Fact) []string {
	seen := map[string]bool{}
	var out []string
	for _, f := range list {
		if name := f.ProjectName(); name != "" && !seen[name] {
			seen[name] = true
			out = append(out, name)
		}
	}
	sort.Strings(out)
	return out
}

type vocabPair struct {
	subject, relation string
	count             int
}

func vocabulary(all []facts.Fact) []vocabPair {
	counts := map[[2]string]int{}
	for _, f := range all {
		counts[[2]string{f.Subject, f.Relation}]++
	}
	out := make([]vocabPair, 0, len(counts))
	for pair, n := range counts {
		out = append(out, vocabPair{pair[0], pair[1], n})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].subject != out[j].subject {
			return out[i].subject < out[j].subject
		}
		return out[i].relation < out[j].relation
	})
	return out
}

func topicMap(list []facts.Fact) map[string][]facts.Fact {
	topics := map[string][]facts.Fact{}
	for _, f := range list {
		for _, slug := range f.Topics {
			topics[slug] = append(topics[slug], f)
		}
	}
	for slug := range topics {
		sort.Slice(topics[slug], func(i, j int) bool { return topics[slug][i].ID < topics[slug][j].ID })
	}
	return topics
}

func topicPage(slug string, members []facts.Fact) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Topic: %s\n\n", slug)
	b.WriteString(generatedHeader)
	b.WriteString("\n")
	for _, f := range members {
		tag := ""
		if f.Status == facts.StatusProposed {
			tag = "[proposed] "
		}
		fmt.Fprintf(&b, "- [[%s]] — %s%s (%s)\n", f.ID, tag, f.Title, f.Scope)
	}
	return b.String()
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
